version: "2"
services:
  streamripper:
    build:
      context: .
      dockerfile: Dockerfile-streamripper
    restart: unless-stopped
    volumes:
      - ./streamripper-tmp:/root/stream
    command: '/root/streamripper ${STREAMRIPPER_ARGS}'
  notify:
    build:
      context: .
      dockerfile: Dockerfile-notify
    restart: unless-stopped
    volumes:
      - ./streamripper-tmp:/root/from
      - ./streamripper-nginx:/root/to
    command: './start.sh /root/from /root/to'
    environment:
      - TGBOT_URL=${TGBOT_URL}
      - TGBOT_CHATID=${TGBOT_CHATID}
      - WEB_HREF_PREFIX=${WEB_HREF_PREFIX}
      - CONSOLE_VERBOSE=${CONSOLE_VERBOSE}
      - DAYS_TO_KEEP_INCOMPLETE=${DAYS_TO_KEEP_INCOMPLETE}
      - REGEX_2_DEL=${REGEX_2_DEL}
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "${NGINX_PORT}:80"
    restart: unless-stopped
    volumes:
      - ./streamripper-nginx:/usr/share/nginx/html
